// api/nav.js — Generates Hungarian NAV Online Számla XML 3.0 for manual upload
// The user downloads this file and uploads it to onlineszamla.nav.gov.hu
// This covers the RTIR (Real-Time Invoice Reporting) obligation for Hungarian taxpayers
// POST with invoice data, returns XML string

export default async function handler(req, res) {
  if (req.method !== "POST") return res.status(405).json({ error: "Method not allowed" });

  const {
    // Seller (Hungarian taxpayer)
    sellerName, sellerTaxNumber,  // Hungarian format: 12345678-1-01
    sellerVATGroupNumber,         // Optional — if part of VAT group
    sellerStreet, sellerCity, sellerPostalCode,
    sellerBankAccount,            // IBAN
    sellerEmail,
    // Buyer
    buyerName, buyerTaxNumber,    // Hungarian or EU VAT number
    buyerStreet, buyerCity, buyerPostalCode, buyerCountry,
    buyerIsEU,                    // boolean — EU cross-border
    // Invoice
    invoiceNumber,
    issueDate,                    // YYYY-MM-DD
    deliveryDate,                 // YYYY-MM-DD (teljesítés dátuma)
    dueDate,                      // YYYY-MM-DD
    currency,                     // HUF or EUR etc
    exchangeRate,                 // If not HUF — ECB rate on invoice date
    note,
    // Lines
    lines,                        // [{ desc, qty, unit, unitPrice, vatCode, vatRate, lineNet, lineVat, lineGross }]
    // Totals
    invoiceNetAmount,
    invoiceVatAmount,
    invoiceGrossAmount,
    // Flags
    reverseCharge,                // EU cross-border B2B — eusAfa case
    vatExempt,                    // §19 / AAM
  } = req.body;

  // Validate required fields
  if (!sellerTaxNumber) return res.status(400).json({ error: "sellerTaxNumber required (format: 12345678-1-01)" });
  if (!invoiceNumber)   return res.status(400).json({ error: "invoiceNumber required" });
  if (!issueDate)       return res.status(400).json({ error: "issueDate required" });
  if (!lines || !lines.length) return res.status(400).json({ error: "lines required" });

  const cur = currency || "HUF";
  const esc = (s) => String(s || "").replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
  const fmt = (n) => Number(n || 0).toFixed(2);

  // NAV VAT codes
  // 27 = standard HU rate, AAM = exempt, EUT = EU reverse charge
  const getVatCode = (line) => {
    if (reverseCharge) return "EUT";   // EU cross-border reverse charge
    if (vatExempt)     return "AAM";   // Hungarian small business exemption
    return line.vatCode || "27";       // Default Hungarian 27%
  };

  // Determine if this is EU cross-border (eusAfa) — no NAV submission needed
  const isEUSAfa = reverseCharge && buyerIsEU;

  const now = new Date();
  const timestamp = now.toISOString().replace(/\.\d{3}Z$/, "+00:00");

  const linesXML = (lines || []).map((line, i) => `
    <line>
      <lineNumber>${i + 1}</lineNumber>
      <lineDescription>${esc(line.desc)}</lineDescription>
      <quantity>${Number(line.qty || 1).toFixed(6)}</quantity>
      <unitOfMeasureOwn>${esc(line.unit || "db")}</unitOfMeasureOwn>
      <unitPrice>${fmt(line.unitPrice)}</unitPrice>
      <lineNetAmountData>
        <lineNetAmount>${fmt(line.lineNet)}</lineNetAmount>
        <lineNetAmountHUF>${cur === "HUF" ? fmt(line.lineNet) : fmt(line.lineNet * (exchangeRate || 1))}</lineNetAmountHUF>
      </lineNetAmountData>
      <lineVatRate>
        <vatPercentage>${Number(line.vatRate || 0).toFixed(2)}</vatPercentage>
      </lineVatRate>
      <lineVatData>
        <lineVatAmount>${fmt(line.lineVat || 0)}</lineVatAmount>
        <lineVatAmountHUF>${cur === "HUF" ? fmt(line.lineVat || 0) : fmt((line.lineVat || 0) * (exchangeRate || 1))}</lineVatAmountHUF>
      </lineVatData>
      <lineGrossAmountData>
        <lineGrossAmountNormal>${fmt(line.lineGross)}</lineGrossAmountNormal>
        <lineGrossAmountNormalHUF>${cur === "HUF" ? fmt(line.lineGross) : fmt(line.lineGross * (exchangeRate || 1))}</lineGrossAmountNormalHUF>
      </lineGrossAmountData>
    </line>`).join("");

  const xml = `<?xml version="1.0" encoding="UTF-8"?>
<InvoiceData xmlns="http://schemas.nav.gov.hu/OSA/3.0/data"
             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:schemaLocation="http://schemas.nav.gov.hu/OSA/3.0/data invoiceData.xsd">

  <!-- NAV Online Számla XML 3.0 — Generated by InvoiceAI (invoice-ai.de) -->
  <!-- Upload to: https://onlineszamla.nav.gov.hu -->
  <!-- Schema version: 3.0 -->

  <invoiceNumber>${esc(invoiceNumber)}</invoiceNumber>
  <invoiceIssueDate>${esc(issueDate)}</invoiceIssueDate>
  <completenessIndicator>false</completenessIndicator>

  <invoiceMain>
    <invoice>
      <invoiceReference>
        <originalInvoiceNumber>${esc(invoiceNumber)}</originalInvoiceNumber>
        <modifyWithoutMaster>false</modifyWithoutMaster>
      </invoiceReference>

      <invoiceHead>
        <supplierInfo>
          <supplierTaxNumber>
            <taxpayerId>${esc(sellerTaxNumber.split("-")[0] || sellerTaxNumber)}</taxpayerId>
            <vatCode>${esc(sellerTaxNumber.split("-")[1] || "1")}</vatCode>
            <countyCode>${esc(sellerTaxNumber.split("-")[2] || "01")}</countyCode>
          </supplierTaxNumber>
          <supplierName>${esc(sellerName)}</supplierName>
          <supplierAddress>
            <detailedAddress>
              <countryCode>HU</countryCode>
              <postalCode>${esc(sellerPostalCode || "")}</postalCode>
              <city>${esc(sellerCity || "")}</city>
              <streetName>${esc(sellerStreet || "")}</streetName>
            </detailedAddress>
          </supplierAddress>
          ${sellerBankAccount ? `<supplierBankAccountNumber>${esc(sellerBankAccount.replace(/\s/g,""))}</supplierBankAccountNumber>` : ""}
          <individualExemption>${vatExempt ? "true" : "false"}</individualExemption>
          ${sellerEmail ? `<supplierEmail>${esc(sellerEmail)}</supplierEmail>` : ""}
        </supplierInfo>

        <customerInfo>
          <customerVatStatus>${buyerIsEU ? "OTHER" : (buyerTaxNumber ? "DOMESTIC" : "PRIVATE_PERSON")}</customerVatStatus>
          ${buyerTaxNumber && !buyerIsEU ? `<customerTaxNumber>
            <taxpayerId>${esc(buyerTaxNumber.split("-")[0] || buyerTaxNumber)}</taxpayerId>
          </customerTaxNumber>` : ""}
          ${buyerTaxNumber && buyerIsEU ? `<customerVatData>
            <customerVatNumber>
              <communityVatNumber>${esc(buyerTaxNumber)}</communityVatNumber>
            </customerVatNumber>
          </customerVatData>` : ""}
          <customerName>${esc(buyerName)}</customerName>
          <customerAddress>
            <detailedAddress>
              <countryCode>${esc(buyerCountry || "HU")}</countryCode>
              ${buyerPostalCode ? `<postalCode>${esc(buyerPostalCode)}</postalCode>` : ""}
              ${buyerCity ? `<city>${esc(buyerCity)}</city>` : ""}
              ${buyerStreet ? `<streetName>${esc(buyerStreet)}</streetName>` : ""}
            </detailedAddress>
          </customerAddress>
        </customerInfo>

        <invoiceDetail>
          <invoiceCategory>NORMAL</invoiceCategory>
          <invoiceDeliveryDate>${esc(deliveryDate || issueDate)}</invoiceDeliveryDate>
          ${dueDate ? `<paymentDate>${esc(dueDate)}</paymentDate>` : ""}
          <invoiceAppearance>ELECTRONIC</invoiceAppearance>
          ${isEUSAfa ? "<eusAfa>true</eusAfa>" : ""}
          ${note ? `<additionalInvoiceData>
            <dataName>NOTE</dataName>
            <dataDescription>Megjegyzés / Note</dataDescription>
            <dataValue>${esc(note)}</dataValue>
          </additionalInvoiceData>` : ""}
        </invoiceDetail>
      </invoiceHead>

      <invoiceLines>
        <mergedItemIndicator>false</mergedItemIndicator>
        ${linesXML}
      </invoiceLines>

      <invoiceSummary>
        <summaryNormal>
          <summaryByVatRate>
            <vatRate>
              ${reverseCharge ? "<vatDomesticReverseCharge>true</vatDomesticReverseCharge>" :
                vatExempt ? "<vatExemption><caseAAM>true</caseAAM></vatExemption>" :
                `<vatPercentage>${Number(lines && lines[0] ? lines[0].vatRate : 27).toFixed(2)}</vatPercentage>`}
            </vatRate>
            <vatRateNetData>
              <vatRateNetAmount>${fmt(invoiceNetAmount)}</vatRateNetAmount>
              <vatRateNetAmountHUF>${cur === "HUF" ? fmt(invoiceNetAmount) : fmt(invoiceNetAmount * (exchangeRate || 1))}</vatRateNetAmountHUF>
            </vatRateNetData>
            <vatRateVatData>
              <vatRateVatAmount>${fmt(invoiceVatAmount || 0)}</vatRateVatAmount>
              <vatRateVatAmountHUF>${cur === "HUF" ? fmt(invoiceVatAmount || 0) : fmt((invoiceVatAmount || 0) * (exchangeRate || 1))}</vatRateVatAmountHUF>
            </vatRateVatData>
          </summaryByVatRate>
          <invoiceNetAmount>${fmt(invoiceNetAmount)}</invoiceNetAmount>
          <invoiceNetAmountHUF>${cur === "HUF" ? fmt(invoiceNetAmount) : fmt(invoiceNetAmount * (exchangeRate || 1))}</invoiceNetAmountHUF>
          <invoiceVatAmount>${fmt(invoiceVatAmount || 0)}</invoiceVatAmount>
          <invoiceVatAmountHUF>${cur === "HUF" ? fmt(invoiceVatAmount || 0) : fmt((invoiceVatAmount || 0) * (exchangeRate || 1))}</invoiceVatAmountHUF>
        </summaryNormal>
        <summaryGrossData>
          <invoiceGrossAmount>${fmt(invoiceGrossAmount)}</invoiceGrossAmount>
          <invoiceGrossAmountHUF>${cur === "HUF" ? fmt(invoiceGrossAmount) : fmt(invoiceGrossAmount * (exchangeRate || 1))}</invoiceGrossAmountHUF>
        </summaryGrossData>
      </invoiceSummary>
    </invoice>
  </invoiceMain>

</InvoiceData>`;

  res.setHeader("Content-Type", "application/xml; charset=utf-8");
  res.setHeader("Content-Disposition", `attachment; filename="${invoiceNumber.replace(/[^a-zA-Z0-9-_]/g,"_")}_NAV.xml"`);
  return res.status(200).send(xml.trim());
}
